In [2]:
import numpy as np

In [3]:
import pandas as pd 

In [5]:
data = np.load('training.npy')

In [6]:
print(data)

[[  1.37638898   1.37474459   1.41339168 ...  -3.64420375 -13.
   -6.33353557]
 [  1.60390447   1.60932309   1.62882618 ... -11.7751447  -13.
   -1.69429515]
 [  1.47830391   1.48413347   1.53570068 ...  -0.16115065 -13.
  -10.57995389]
 ...
 [  1.45884248   1.44874173   1.46072284 ...  -8.70716468 -13.
   -3.88200321]
 [  1.54077875   1.52329252   1.52582576 ...  -3.10154844  -8.44121
    1.13263478]
 [  1.61096586   1.63717685   1.66279134 ... -11.15088167 -13.
   -5.22960925]]


In [7]:
pd.DataFrame(data)

0         1         2         3         4         5         6   \
0      1.376389  1.374745  1.413392  1.450904  1.466375  1.443057  1.471660   
1      1.603904  1.609323  1.628826  1.620339  1.637257  1.658848  1.646935   
2      1.478304  1.484133  1.535701  1.549377  1.562368  1.535739  1.546677   
3      1.376006  1.374236  1.381826  1.371236  1.372663  1.391107  1.391560   
4      1.563088  1.574923  1.570010  1.562674  1.564904  1.566797  1.572265   
...         ...       ...       ...       ...       ...       ...       ...   
79994  1.547858  1.541549  1.577890  1.592368  1.614620  1.588436  1.606700   
79995  1.690129  1.685105  1.697325  1.695480  1.694271  1.688963  1.693295   
79996  1.458842  1.448742  1.460723  1.462699  1.458183  1.472587  1.467903   
79997  1.540779  1.523293  1.525826  1.527753  1.527622  1.524317  1.523190   
79998  1.610966  1.637177  1.662791  1.642905  1.654042  1.662262  1.666162   

             7         8         9         10        11        12  \
0      1.432622  1.478647  1.517601  1.533182  1.553194  1.544717   
1      1.654072  1.682700  1.702930  1.704248  1.688455  1.672496   
2      1.523513  1.562554  1.594719  1.594487  1.615531  1.614822   
3      1.388384  1.409598  1.428910  1.426103  1.415693  1.405483   
4      1.567724  1.556413  1.575183  1.565158  1.564148  1.560290   
...         ...       ...       ...       ...       ...       ...   
79994  1.582812  1.615082  1.660816  1.671223  1.710971  1.688608   
79995  1.691038  1.683915  1.691066  1.685970  1.703655  1.694314   
79996  1.461175  1.486257  1.493419  1.499475  1.497590  1.472219   
79997  1.530734  1.522610  1.535232  1.524432  1.534980  1.523554   
79998  1.666940  1.697723  1.720909  1.719560  1.712996  1.698128   

                13         14         15        16         17  
0      2712.064538  -9.203615  -3.644204 -13.00000  -6.333536  
1      2392.301318  -0.457763 -11.775145 -13.00000  -1.694295  
2      1892.056087  -4.744679  -0.161151 -13.00000 -10.579954  
3      2258.214546  -6.513760 -12.833482 -13.00000  -5.830304  
4      2752.310725 -10.117546  -7.401393 -13.00000  -1.797602  
...            ...        ...        ...       ...        ...  
79994  2380.950717  -4.643444  -0.028175 -13.00000  -2.192794  
79995  2608.258100 -12.802186  -1.157247 -13.00000   0.871717  
79996  2406.213138  -5.147355  -8.707165 -13.00000  -3.882003  
79997  1234.629377  -3.092740  -3.101548  -8.44121   1.132635  
79998  2526.404810  -0.426298 -11.150882 -13.00000  -5.229609  

[79999 rows x 18 columns]

In [8]:
data1 = pd.DataFrame(data)
data1.describe()

0             1             2             3             4   \
count  79999.000000  79999.000000  79999.000000  79999.000000  79999.000000   
mean       1.454087      1.460860      1.471500      1.473332      1.475104   
std        0.100177      0.099737      0.097908      0.097393      0.097745   
min        1.045721      1.071769      1.088413      1.082273      1.100168   
25%        1.393057      1.400075      1.409575      1.411105      1.411562   
50%        1.444713      1.451744      1.462259      1.464455      1.465410   
75%        1.511177      1.518548      1.530472      1.533465      1.536275   
max        1.795864      1.792027      1.796910      1.794441      1.794951   

                 5             6             7             8             9   \
count  79999.000000  79999.000000  79999.000000  79999.000000  79999.000000   
mean       1.478335      1.479885      1.474180      1.488665      1.501364   
std        0.098440      0.098311      0.098774      0.099447      0.100692   
min        1.093517      1.101699      1.096448      1.132823      1.147489   
25%        1.414192      1.415398      1.410607      1.421834      1.430796   
50%        1.468031      1.470094      1.464846      1.477275      1.489207   
75%        1.539306      1.540799      1.534304      1.550911      1.566310   
max        1.792878      1.793002      1.796757      1.795992      1.805131   

                 10            11            12            13            14  \
count  79999.000000  79999.000000  79999.000000  79999.000000  79999.000000   
mean       1.504155      1.505752      1.498714   1699.361211     -6.511295   
std        0.100698      0.101606      0.101594    692.758034      3.746558   
min        1.150093      1.157484      1.151066    500.028196    -12.999771   
25%        1.433668      1.433606      1.426953   1098.445322     -9.749975   
50%        1.492377      1.493558      1.486347   1701.891271     -6.536191   
75%        1.569105      1.572194      1.564693   2296.995517     -3.268591   
max        1.813981      1.806278      1.802213   2899.998609     -0.000062   

                 15            16            17  
count  79999.000000  79999.000000  79999.000000  
mean      -6.487226    -10.275925     -5.501269  
std        3.751886      4.033091      4.329785  
min      -12.999850    -13.000000    -12.999503  
25%       -9.734475    -13.000000     -9.255937  
50%       -6.492825    -13.000000     -5.481351  
75%       -3.225007     -7.741483     -1.772234  
max       -0.000335     -0.000260      1.999499

array([ 1.34960585e+00,  1.36544845e+00,  1.36899392e+00,  1.36695074e+00,
        1.36632333e+00,  1.38724172e+00,  1.37638759e+00,  1.35917400e+00,
        1.39788990e+00,  1.40856361e+00,  1.40344853e+00,  1.41154531e+00,
        1.39562654e+00,  1.43278108e+03, -6.22162146e+00, -5.95690075e+00,
       -9.80380251e+00, -9.77948869e+00])

In [ ]:
import matplotlib.pyplot as plt
x = np.array((i) for i in range(80000)) 
y = data1['13']

In [3]:
data = np.load('training.npy')

In [4]:
data.tofile('training_data.csv', sep = ',')

In [10]:
data1.to_csv('train_data.csv', sep='\t', encoding='utf-8')

In [4]:
hdata = np.load('training.npy')

In [5]:
print(hdata)

[[  1.37638898   1.37474459   1.41339168 ...  -3.64420375 -13.
   -6.33353557]
 [  1.60390447   1.60932309   1.62882618 ... -11.7751447  -13.
   -1.69429515]
 [  1.47830391   1.48413347   1.53570068 ...  -0.16115065 -13.
  -10.57995389]
 ...
 [  1.45884248   1.44874173   1.46072284 ...  -8.70716468 -13.
   -3.88200321]
 [  1.54077875   1.52329252   1.52582576 ...  -3.10154844  -8.44121
    1.13263478]
 [  1.61096586   1.63717685   1.66279134 ... -11.15088167 -13.
   -5.22960925]]


In [7]:
df11 = pd.DataFrame(hdata)

In [15]:
df112 = df11.iloc[:,13:]

In [16]:
df112

13         14         15        16         17
0      2712.064538  -9.203615  -3.644204 -13.00000  -6.333536
1      2392.301318  -0.457763 -11.775145 -13.00000  -1.694295
2      1892.056087  -4.744679  -0.161151 -13.00000 -10.579954
3      2258.214546  -6.513760 -12.833482 -13.00000  -5.830304
4      2752.310725 -10.117546  -7.401393 -13.00000  -1.797602
...            ...        ...        ...       ...        ...
79994  2380.950717  -4.643444  -0.028175 -13.00000  -2.192794
79995  2608.258100 -12.802186  -1.157247 -13.00000   0.871717
79996  2406.213138  -5.147355  -8.707165 -13.00000  -3.882003
79997  1234.629377  -3.092740  -3.101548  -8.44121   1.132635
79998  2526.404810  -0.426298 -11.150882 -13.00000  -5.229609

[79999 rows x 5 columns]

In [8]:
df111 = df11.iloc[:,:13]

In [9]:
df111

0         1         2         3         4         5         6   \
0      1.376389  1.374745  1.413392  1.450904  1.466375  1.443057  1.471660   
1      1.603904  1.609323  1.628826  1.620339  1.637257  1.658848  1.646935   
2      1.478304  1.484133  1.535701  1.549377  1.562368  1.535739  1.546677   
3      1.376006  1.374236  1.381826  1.371236  1.372663  1.391107  1.391560   
4      1.563088  1.574923  1.570010  1.562674  1.564904  1.566797  1.572265   
...         ...       ...       ...       ...       ...       ...       ...   
79994  1.547858  1.541549  1.577890  1.592368  1.614620  1.588436  1.606700   
79995  1.690129  1.685105  1.697325  1.695480  1.694271  1.688963  1.693295   
79996  1.458842  1.448742  1.460723  1.462699  1.458183  1.472587  1.467903   
79997  1.540779  1.523293  1.525826  1.527753  1.527622  1.524317  1.523190   
79998  1.610966  1.637177  1.662791  1.642905  1.654042  1.662262  1.666162   

             7         8         9         10        11        12  
0      1.432622  1.478647  1.517601  1.533182  1.553194  1.544717  
1      1.654072  1.682700  1.702930  1.704248  1.688455  1.672496  
2      1.523513  1.562554  1.594719  1.594487  1.615531  1.614822  
3      1.388384  1.409598  1.428910  1.426103  1.415693  1.405483  
4      1.567724  1.556413  1.575183  1.565158  1.564148  1.560290  
...         ...       ...       ...       ...       ...       ...  
79994  1.582812  1.615082  1.660816  1.671223  1.710971  1.688608  
79995  1.691038  1.683915  1.691066  1.685970  1.703655  1.694314  
79996  1.461175  1.486257  1.493419  1.499475  1.497590  1.472219  
79997  1.530734  1.522610  1.535232  1.524432  1.534980  1.523554  
79998  1.666940  1.697723  1.720909  1.719560  1.712996  1.698128  

[79999 rows x 13 columns]

In [10]:
xn_train = df111.to_numpy()

In [11]:
print(xn_train)

[[1.37638898 1.37474459 1.41339168 ... 1.5331821  1.55319437 1.54471723]
 [1.60390447 1.60932309 1.62882618 ... 1.70424847 1.68845492 1.67249611]
 [1.47830391 1.48413347 1.53570068 ... 1.5944868  1.61553135 1.61482229]
 ...
 [1.45884248 1.44874173 1.46072284 ... 1.49947516 1.4975898  1.47221859]
 [1.54077875 1.52329252 1.52582576 ... 1.52443166 1.53497964 1.52355361]
 [1.61096586 1.63717685 1.66279134 ... 1.71956018 1.71299566 1.69812816]]


In [17]:
yn_train = df112.to_numpy()

In [18]:
print(yn_train)

[[ 2.71206454e+03 -9.20361459e+00 -3.64420375e+00 -1.30000000e+01
  -6.33353557e+00]
 [ 2.39230132e+03 -4.57762872e-01 -1.17751447e+01 -1.30000000e+01
  -1.69429515e+00]
 [ 1.89205609e+03 -4.74467893e+00 -1.61150645e-01 -1.30000000e+01
  -1.05799539e+01]
 ...
 [ 2.40621314e+03 -5.14735538e+00 -8.70716468e+00 -1.30000000e+01
  -3.88200321e+00]
 [ 1.23462938e+03 -3.09273952e+00 -3.10154844e+00 -8.44121000e+00
   1.13263478e+00]
 [ 2.52640481e+03 -4.26297738e-01 -1.11508817e+01 -1.30000000e+01
  -5.22960925e+00]]


In [20]:
np.save('xn_train',xn_train)

In [21]:
np.save('yn_train',yn_train)